<?php
/**
 * @file
 * Code for the Stanford Exhibition Views feature.
 */

include_once 'stanford_exhibition_views.features.inc';


/**
 * Change title of the homepage block to use upcoming exhibitions when it uses
 * the no results fallback view.
 * @param  [type] $view [description]
 * @return [type]       [description]
 */
function stanford_exhibition_views_views_post_render(&$view) {

  if ($view->name == "stanford_exhibitions" && $view->current_display == "current_exhibitions_block_1_up") {
    if ($view->total_rows == 0) {
      $view->set_title('Upcoming Exhibitions');
    }
  }

}

/**
 * Switches sort ordering when on search page and user selects one date over the
 * other.
 * @param  [type] $view  [description]
 * @param  [type] $query [description]
 * @return [type]        [description]
 */
function stanford_exhibition_views_views_query_alter(&$view, &$query) {
  // Automatically Adjust the sorting for the search page based on the
  // date parameters so that it is logically sorted.
  if ($view->name == "stanford_exhibitions" && $view->current_display == "exhibitions_search") {
    if (!empty($view->exposed_data["field_s_exh_dates_duration_value"]['value']) && empty($view->exposed_data['field_s_exh_dates_duration_value2_1']['value'])) {
      $query->orderby[0]['direction'] = "DESC";
    }
  }

}
